
# ===================================================
# Configuration for SimCLR
# ===================================================

# General
epochs: 200
batch_size: 512
num_workers: 8
eval_every: 5


# Dataset
dataset:
  name: cifar10
  root: ../data/cifar10
  num_classes: 10


# SimCLR settings
encoder:
  backbone: resnet18
  pretrained: False
  zero_init_residual: False

proj_head:
  in_dim: 512
  out_dim: 128

simclr_optim:
  name: lars
  momentum: 0.9
  weight_decay: 0.0005
  eta: 0.001

simclr_scheduler:
  name: warmup_cosine
  warmup_epochs: 10
  start_lr: 1.e-13
  base_lr: 4.8

criterion:
  normalize: True
  temperature: 0.5


# Linear evaluation setting
linear_eval_epochs: 100

clf_optim:
  name: sgd
  lr: 0.1
  weight_decay: 0
  momentum: 0.9
  nesterov: True

clf_scheduler:
  name: cosine
  base_lr: 4.8


# Transforms
train_transform:
  random_crop:
    size: [32, 32]
  random_flip:
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]

val_transform:
  center_crop:
    size: [32, 32]
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]

aug_transform:
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.1
    apply_prob: 0.8
  random_gray:
    p: 0.2
  gaussian_blur:
    sigma: [0.1, 2.0]
    apply_prob: 0.5
  random_crop:
    size: [32, 32]
  random_flip:
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]

