# SimCLR configuration
# Authors: Mukund Varma T, Nishant Prabhu

# General
task: rotnet
dataset: cifar10
batch_size: 128
num_workers: 4
epochs: 100
eval_every: 10
# number of neighbors
n_neighbors: 20

# Data Transforms
train_transform:
  random_resized_crop:
    size: [32, 32]
    scale: [0.2, 1.0]
  to_tensor:
  normalize:

std_transform:
  center_crop:
    size: [32, 32]
  to_tensor:
  normalize:

# Data Loaders
dataloaders:
  train:
    rotnet: [0, 90, 180, 270]
    split: train
    transforms:
      img: train_transform
    return_items: [img]
    shuffle: True
    drop_last: False
    weigh: True
  val:
    split: val
    transforms:
      img: std_transform
    return_items: [img, target]
    shuffle: False
    drop_last: False
  eval_train:
    split: train
    transforms:
      img: std_transform
    return_items: [img, target]
    shuffle: False
    drop_last: False

# Networks
encoder:
  name: resnet18
  zero_init_residual: False

rotnet:
  n_angles: 4

# Optimizers
rotnet_optim:
  name: sgd
  lr: 0.1
  weight_decay: 5.e-04

rotnet_lr_scheduler:
  name: multistep
  milestones: [30, 60, 80]
  gamma: 0.2
  warmup_epochs: 0

# Linear classifier
linear_eval_epochs: 100

clf_optim:
  name: sgd
  lr: 0.1
  weight_decay: 0.0

clf_lr_scheduler:
  name: cosine
