# Self Labelling configuration
# Authors: Mukund Varma T, Nishant Prabhu

# General
task: selflabel
dataset: cifar10
batch_size: 1000
num_workers: 4
epochs: 200
eval_every: 5
cluster_save:

# Data Transforms
aug_transform:
  random_flip:
  random_crop:
    size: [32, 32]
  rand_aug:
    n_aug: 4
  to_tensor:
  normalize:
  cutout:
    n_cuts: 1
    max_len: 16

std_transform:
  center_crop:
    size: [32, 32]
  to_tensor:
  normalize:

# Data Loaders
dataloaders:
  train:
    split: train
    transforms:
      img: std_transform
      img_aug: aug_transform
    return_items: [img, img_aug]
    shuffle: True
  val:
    split: val
    transforms:
      img: std_transform
    return_items: [img, target]
    shuffle: False

# Networks
encoder:
  name: resnet18
  zero_init_residual: False

cluster_head:
  n_clusters: 10
  heads: 1

# Optimizers
selflabel_optim:
  name: adam
  lr: 1.e-04
  weight_decay: 1.e-04

selflabel_lr_scheduler:
  name: NULL
  warmup_epochs: 0

selflabel_criterion:
  confidence: 0.99
