
# SimCLR configuration
# Authors: Mukund Varma T, Nishant Prabhu

# General
task: simclr
epochs: 1
batch_size: 512
num_workers: 8
eval_every: 1
save_every: 1

# Model
encoder:
  name: resnet18
  pretrained: False
  zero_init_residual: False 

head:
  in_dim: 512
  out_dim: 128

optimizer:
  name: sgd
  lr: 1.0
  weight_decay: 1.e-06

scheduler:
  name: cosine
  warmup_epochs: 10

criterion:
  normalize: False
  temperature: 0.5


# Linear classifier
linear_eval_epochs: 1

clf_optimizer:
  name: adam
  lr: 0.01
  weight_decay: 1.e-06

clf_scheduler:
  name: cosine
  warmup_epochs: 10


# Data
dataset:
  name: cifar10
  n_classes: 10
  root: data/cifar10

# Transforms
train_transform:
  random_resized_crop: 
    size: [32, 32]
    scale: [0.008, 1.0]
  random_flip:
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]

val_transform:
  center_crop: 
    size: [32, 32]
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]

aug_transform:
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.1
    apply_prob: 0.8
  random_gray:
    p: 0.2
  gaussian_blur:
    sigma: [0.1,2.0]  
    apply_prob: 0.5
  random_resized_crop: 
    size: [32, 32]
    scale: [0.008, 1.0]
  random_flip:
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]


# Dataset transformations
data_transforms:
  train:
    img: train_transform
  val:
    img: val_transform
  main:
    i: aug_transform
    j: aug_transform


# Dataset return items
train_items: [img, target]
val_items: [img, target]
main_items: [i, j]





