
# SimCLR configuration
# Authors: Mukund Varma T, Nishant Prabhu

# General
task: simclr
dataset: cifar10
batch_size: 256
num_workers: 8
epochs: 1000
eval_every: 100
# number of neighbors
n_neighbors: 20

# Data Transforms
aug_transform:
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.1
    apply_prob: 0.8
  random_gray:
    p: 0.2
  gaussian_blur:
    sigma: [0.1,2.0]  
    apply_prob: 0.5
  random_resized_crop: 
    size: [32, 32]
    scale: [0.008, 1.0]
  random_flip:
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]

std_transform:
  center_crop: 
    size: [32, 32]
  to_tensor:
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std:  [0.2023, 0.1994, 0.2010]

# Data Loaders
dataloaders:
  train:
    split: train
    transforms: 
      i: aug_transform
      j: aug_transform
    return_items: [i, j]
    shuffle: True
    drop_last: True
    weigh: True
  val:
    split: val
    transforms: 
      img: std_transform
    return_items: [img, target]
    shuffle: False
    drop_last: False
  eval_train:
    split: train
    transforms: 
      img: std_transform
    return_items: [img, target]
    shuffle: False
    drop_last: False


# Networks
encoder:
  name: resnet18
  pretrained: False
  zero_init_residual: False 

proj_head:
  in_dim: 512
  out_dim: 128

# Optimizers
simclr_optim:
  name: sgd
  lr: 1.0
  weight_decay: 1.e-06

simclr_lr_scheduler:
  name: cosine
  warmup_epochs: 10

simclr_criterion:
  normalize: False
  temperature: 0.5

# Linear classifier
linear_eval_epochs: 100

clf_optimizer:
  name: sgd
  lr: 0.1
  weight_decay: 0.0

clf_scheduler:
  name: cosine